### ISSUE TITLE
Asset Bundle, not finding any files

### ISSUE THREAD

**Issue by Kurisama91** [gwiazdorrr/BetterStreamingAssets#10]
It's odd but running the application build and run will work but when uploaded to google play and delivered it seems like betterstreamingassets can't find any files.

I'm not getting any crash or error, it's just simply not finding any files when served from Google leading me to think their apk generation maybe moves the location?

**Comment by gwiazdorrr** [comment]
It's all about compression; BSA doesn't support compressed Streaming Assets.

There is some strangeness with App Bundles, even when built and run locally; sometimes some Streaming Assets are compressed, sometimes not. I can't really put my finger on it.

Now, I understand you upload an App Bundle, not an APK?

**Comment by fpv999** [comment]
any news on the issue? Will you be able to add support for compressed assets?

**Comment by gwiazdorrr** [comment]
While it is possible, benefits of Streaming Assets would be lost (instant random access). And I don't have time at the moment.

Is it still broken with latest Unity?

**Comment by gwiazdorrr** [comment]
Woohoo, there's a workaround! 

First there are inconsistent accounts of what makes stuff in Streaming Assets compressed:
https://issuetracker.unity3d.com/issues/android-loading-assets-from-assetbundles-takes-significantly-more-time-when-the-project-is-built-as-an-aab
https://forum.unity.com/threads/asset-bundles-in-streamingassets-directory-can-load-slower-when-building-the-android-app-bundle.711752/
https://forum.unity.com/threads/streamingassets-files-are-compressed-in-apk-when-build-app-bundle-google-play-option-is-used.739967/

However, it seems that as of now the workaround is to **avoid uppercase letters in file names.**

**Comment by pepoon** [comment]
Hello guys,
My StreamingAssets folder is all using uppercase letteers, any other way to fix this issue?
Thanks.

**Comment by gwiazdorrr** [comment]
Lowercase for folders too?

**Comment by pepoon** [comment]
The generated .aabb bundle contains a bin folder (not generated by us) where it contains upper case files & folders.

\assets\bin\Data\1408c9cfe620b824ba12e140640118a8
\assets\bin\Data\2e7ad78679bf43e4eba31c3c5e7a8a4a
\assets\bin\Data\3f5b5dff67a942289a9defa416b206f3
\assets\bin\Data\9af043668d149e041abe9f0adb94dd8a
\assets\bin\Data\a084e85e774d0184cb0ec4b8aa2944e0
\assets\bin\Data\bec9e088313381a42bc3cc5cbd54ce69
\assets\bin\Data\boot.config
\assets\bin\Data\c5cb98b65f5f94342a3f8787e26895d2
\assets\bin\Data\d82c1b31c7e74239bff1220585707d2b
\assets\bin\Data\ef5adf5b9dc526c43a1990bee79cebd2
\assets\bin\Data\f952c082cb03451daed3ee968ac6c63e
\assets\bin\Data\fade42e8bc714b018fac513c043d323b
\assets\bin\Data\globalgamemanagers
\assets\bin\Data\globalgamemanagers.assets.split0
\assets\bin\Data\globalgamemanagers.assets.split1
\assets\bin\Data\level0
\assets\bin\Data\sharedassets0.assets
\assets\bin\Data\unity default resources
\assets\bin\Data\Managed\etc\mono\browscap.ini
\assets\bin\Data\Managed\etc\mono\config
\assets\bin\Data\Managed\etc\mono\2.0\DefaultWsdlHelpGenerator.aspx
\assets\bin\Data\Managed\etc\mono\2.0\machine.config
\assets\bin\Data\Managed\etc\mono\2.0\settings.map
\assets\bin\Data\Managed\etc\mono\2.0\web.config
\assets\bin\Data\Managed\etc\mono\2.0\Browsers\Compat.browser
\assets\bin\Data\Managed\etc\mono\4.0\DefaultWsdlHelpGenerator.aspx
\assets\bin\Data\Managed\etc\mono\4.0\machine.config
\assets\bin\Data\Managed\etc\mono\4.0\settings.map
\assets\bin\Data\Managed\etc\mono\4.0\web.config
\assets\bin\Data\Managed\etc\mono\4.0\Browsers\Compat.browser
\assets\bin\Data\Managed\etc\mono\4.5\DefaultWsdlHelpGenerator.aspx
\assets\bin\Data\Managed\etc\mono\4.5\machine.config
\assets\bin\Data\Managed\etc\mono\4.5\settings.map
\assets\bin\Data\Managed\etc\mono\4.5\web.config
\assets\bin\Data\Managed\etc\mono\4.5\Browsers\Compat.browser
\assets\bin\Data\Managed\etc\mono\mconfig\config.xml
\assets\bin\Data\Managed\Metadata\global-metadata.dat
\assets\bin\Data\Managed\Resources\Ionic.Zip.dll-resources.dat
\assets\bin\Data\Managed\Resources\mscorlib.dll-resources.dat
\assets\bin\Data\Managed\Resources\System.Data.dll-resources.dat
\assets\bin\Data\Resources\unity_builtin_extra

**Comment by pepoon** [comment]
Upgrading from unity 2018.4.5f1 to 2019.3.14 fixed the problem.
Thanks to gwiazdorrr to help me figure it out.

**Comment by XLIVE99** [comment]
In my project i have "GoogleService-Info.plist" file in StreamingAssets folder. I assume i mustn't change its name because i think its auto generated file. Will it cause the problem again? (Other files and folders are lowercase)
(Sorry for my english)

**Comment by anandmulay3** [comment]
i tried to update the project as suggested by @pepoon , tried 2019.3.14 and 2019.4 LTS latest version also but still its not working , files in streaming folder i renamed it to lowercase characters already.

**Comment by pepoon** [comment]
@anandmulay3 Im only using lowcase chars and underscores '_'. Nothing else.

**Comment by anandmulay3** [comment]
@pepoon any numbers or space between two words??

**Comment by gtoto007** [comment]
This issue is present in linked in readme but here it is closed. So this issue is still open?

**Comment by gwiazdorrr** [comment]
I have not tested this with recent Unity versions. The issue is linked to for context, link and explanation.

**Comment by SunHowe** [comment]
This may not be a upper-case issue, but rather an issue with gradle's nocompress setting when some unity versions export android projects. The solution is as follows:

![image](https://github.com/user-attachments/assets/e2ad095c-cc59-4b6a-a849-14e867093082)
![image](https://github.com/user-attachments/assets/c3a124c0-08e5-4f38-b08d-84640ab1e0d3)
![image](https://github.com/user-attachments/assets/97f73219-c512-4da5-8d75-a3697601eef0)
```
unityStreamingAssets=.unity3d, .gitkeep, .rawfile, .bundle, .version, .bytes, .hash**STREAMING_ASSETS**
```
