### ISSUE TITLE
How to load an Audio ?

### ISSUE THREAD

**Issue by LauraLaureus** [gwiazdorrr/BetterStreamingAssets#12]
Hi! I'm trying to load an Audio using this library. Is there any implemented way to do it or should I try to find a way to convert byte array to audioclip ?

Thanks in advantage.

**Comment by gwiazdorrr** [comment]
This plug-in let's you read raw files from Streaming Assets; what you do with the bytes you get is up to you.

Generally speaking, if you want to read some Unity assets from Streaming Assets, you should use Asset Bundles; IIRC they can read directly from Streaming Assets too. More info: https://docs.unity3d.com/ScriptReference/AssetBundle.LoadFromFile.html
