### ISSUE TITLE
how to load textures from streaming assets

### ISSUE THREAD

**Issue by TheBricktop** [gwiazdorrr/BetterStreamingAssets#13]
How can I load a image stack from steaming asses?

**Comment by gwiazdorrr** [comment]
What's a image stack?

**Comment by TheBricktop** [comment]
Well, bunch of images but ive managed to read bytes and load them to texture with everything in correct order.

**Comment by gwiazdorrr** [comment]
Well you can load bytes and call Texture2D.LoadImage on each of the files... that however would be slow (runtime decompression) and inefficient (will be loaded as a RGBA texture, uncompressed). 

You're better of using asset bundles here. Build them, place them in the Streaming Assets and load them using Asset Bundles API.
