### ISSUE TITLE
Why ignore ZipArchive?

### ISSUE THREAD

**Issue by Leuconoe** [gwiazdorrr/BetterStreamingAssets#14]
hello,
I need to load ZipArchive from the streamingAsset folder.
Is there an important reason for blocking this feature?

**Comment by gwiazdorrr** [comment]
It's not blocked in any way. BSA can't load files that are compressed in APK archive (the main one). If your file is not compressed as a part of APK, but you compressed it on your own, that's fine - you do whatever you want with the Streams/bytes you get.
