### ISSUE TITLE
SubReadOnlyStream can Seek but cannot set Position

### ISSUE THREAD

**Issue by Lyyy** [gwiazdorrr/BetterStreamingAssets#19]
Hi,

Thank you for your very handful plugin :)

I'm just disappointed because I wanted to use it on my project as-is, without modification, but I need to set position on a SubReadOnlyStream, which can be done as it can seek. But SubReadOnlyStream throws when trying to set position. Why ?

I would suggest replacing the NotSupportedException throw by something like this : m_position = m_offset + value;

Also you have a double semicolon line 57 in the same class.

Thanks !

**Comment by gwiazdorrr** [comment]
You're absolutely right. You know, you could submit pull request and the credit would be forever yours ;)

**Comment by Lyyy** [comment]
#20

**Comment by gwiazdorrr** [comment]
Merged c598c64f08824fa859160909cd4e2335f541702a
