### ISSUE TITLE
How to read from StreamingAssets folder

### ISSUE THREAD

**Issue by RedFour** [gwiazdorrr/BetterStreamingAssets#2]
I'm trying to use this for StreamingAssets and cannot get it to work. I'm getting an error "IOException: Invalid characters" when I try to read from an existing json file.

I tried replacing File.ReadAllText(filePath) with BetterStreamingAssets.ReadAllText(filePath). But got the error above. Can you provide documentation on how to read from the StreamingAssets folder?

Below is my code that's using File to read and write, but it doesn't work on Android. How do I use your plugin?

```C#
public void LoadLocalizedText()
    {
        LocalizationData.localizedText = new StringStringDictionary();
        string filePath = Path.Combine(Application.streamingAssetsPath, fileName + ".json").Replace("\\", "/");
		Debug.Log(filePath);
        if (File.Exists(filePath))
        {		
			Debug.Log("file exist");	
            string dataAsJson = File.ReadAllText(filePath);
            JsonUtility.FromJsonOverwrite(dataAsJson, LocalizationData.localizedText);
        }
        else
        {
            Debug.LogError("Cannot find localization file!");
        }
    }
```

```C#
public void SaveLocalizedText()
    {
        string filePath = Path.Combine(Application.streamingAssetsPath, fileName + ".json");
        string jsonData = JsonUtility.ToJson(LocalizationData.localizedText);
        File.WriteAllText(filePath, jsonData);
    }
```

**Comment by gwiazdorrr** [comment]
If you had your paths quoted, then I've just pushed a fix: https://github.com/gwiazdorrr/BetterStreamingAssets/commit/7458ed2cca27659c47e127d3cd5ab8ed94bde94a. Let me know if that was it and whether it works or not.

FYI, invalid characters are defined here: https://github.com/gwiazdorrr/BetterStreamingAssets/blob/a98d01070a43e5e916dc394213c870eb1fecc304/Assets/Plugins/BetterStreamingAssets/BSA_PathUtil.cs#L154.

**Comment by RedFour** [comment]
Hi, I just realized that the path defaults to the StreamingAssets path. 

BetterStreamingAssets.ReadAllText(fileName + ".json"); worked for me.

**Comment by gwiazdorrr** [comment]
Fixed with https://github.com/gwiazdorrr/BetterStreamingAssets/commit/85472a7e481c7494f310b7c03b6b96403ccdf357.

**Comment by RedFour** [comment]
Thank you!

**Comment by Abhijeetk829** [comment]
how to use Better streaming asset to get the path  to read an Mp4 from android Android?
