### ISSUE TITLE
How about make this plugin as a "Package" in "Package Manager"?

### ISSUE THREAD

**Issue by ladepensy** [gwiazdorrr/BetterStreamingAssets#28]
https://docs.unity3d.com/Manual/PackagesList.html

**Comment by cathei** [comment]
I've forked this repository to make it Unity Package: [BetterStreamingAssets-Package](https://github.com/cathei/BetterStreamingAssets-Package)

Main purpose is to use from another package of mine, [BakingSheet](https://github.com/cathei/BakingSheet)
However if anyone wants to use BetterStreamingAssets on Package Manager they can use.

I'll set tag for current master branch as `1.0.0` and will increase if any fixes are added.

**Comment by gwiazdorrr** [comment]
I've just added package.json, so this plugin can now be installed using UPM. 

In your fork, please bump the version to 1.6.0 - to keep it with sync with what's on the Asset Store.

**Comment by cathei** [comment]
Hello, @gwiazdorrr and thank you for great project.
I've tested importing your package via UPM, and I can see some issues with it and I think this issue should be reopened.

First, I get error below:
`Asset Packages/com.gwiazdorrr.betterstreamingassets/package.json has no meta file, but it's in an immutable folder. The asset will be ignored.`
The message is constantly logged every time the project is reopened. This would be resolved by adding `package.json.meta` file into this repository.

Second, there is no way for user to open Sample scene:
Opening scene from immutable package is not supported. Instead, it needs to be in `Samples~` folder and package.json should have info about it.

Third, there is no way to exclude Test script from build:
This will be resolved by creating separated assembly definition and move scripts to `Tests` folder.

My fork resolves these issues, if you prefer I can make PR for this.

**Comment by gwiazdorrr** [comment]
Thanks @cathei, thought I could cheap out on this 😄 I will fix these.

I had a look at your fork and this is how I would love it done, but this actually makes preparing releases for the Asset Store more difficult. `package.json` nested somewhere in `Assets`, while ugly, is the acceptable middle-ground.

**Comment by cathei** [comment]
Ah thanks for looking into it :)
I made a `develop` branch and it has the `master` branch as submodule under `Packages` so I can edit with Unity.

While it's not possible in GUI, it is possible to include `Packages` subfolder into `.unitypackage` if you call `AssetDatabase.ExportPackage` from Editor script, if that helps (not sure Unity Assert Store accepts that way, though).

**Comment by gwiazdorrr** [comment]
There have been some changes in the Asset Store Tools recently, but I haven't had a good look yet. Old ones were a black box, basically.

Are there any downsides to the submodule workflow? Seems like a silver bullet at first glance.

**Comment by cathei** [comment]
I didn't have any problem so far other than just have to manage two branches.
I took this approach from quite popular repo [ParticleEffectForUGUI](https://github.com/mob-sakai/ParticleEffectForUGUI), and it seems like operating well.

**Comment by gwiazdorrr** [comment]
Sound good. Create a PR please, I'll merge it.

**Comment by gwiazdorrr** [comment]
Thanks again!
