### ISSUE TITLE
Question about file name lowercase

### ISSUE THREAD

**Issue by li5414** [gwiazdorrr/BetterStreamingAssets#29]
Do i need to change folder name in Streaming Assets to lowercase ？not filename

**Comment by gwiazdorrr** [comment]
I don't know, as this stems somewhere from deep within Unity build process and I am not terribly eager to jump into this. Tbh I am not even sure this is still a thing in the latest Unity (never was 100% reproducible afaik). My advice is make a build and then inspect the archive with zipinfo/7z/whatever to see if files are compressed or not.

**Comment by gwiazdorrr** [comment]
Leaving this open until this gets verified.

**Comment by gwiazdorrr** [comment]
Finally nailed this down with a8eeccb6938d22de7f48c951b848767ebba46c47. Do not use non-ASCII characters are they will possibly result in Streaming Assets being compressed.

**Comment by gwiazdorrr** [comment]
I think this can be closed for now. Tried to reproduce this with 2020.3 and bundletool, but no amount of uppercases resulted in compressed Streaming Assets. Perhaps this got fixed along the way.  My suggestion is use upper case with care in case it gets broken again.
