### ISSUE TITLE
On Android the seperator char "\" gives Directory Not Found Exception 

### ISSUE THREAD

**Issue by bariscigal** [gwiazdorrr/BetterStreamingAssets#3]
As  in the example of the asset, using the GetFile() with the "\\" path returns a "Directory not found exception" . (Line 389)

Changing the code to this:
string sep = Path.DirectorySeparatorChar.ToString();
string[] paths = BetterStreamingAssets.GetFiles(sep+sep, "*.xml", SearchOption.AllDirectories); 

solves the issue.

**Comment by gwiazdorrr** [comment]
I am unable to reproduce it. Could you paste the code verbatim?

**Comment by Kurisama91** [comment]
Thank god for this issue ticket. I ran into the same issue as well and the proposed fix worked as well for me.

Further info if it helps, I'm running the latest android P on the Pixel XL 3 and using Unity3D 2018.4.0f1

This issue crops up when you run it on device, not in editor.
