### ISSUE TITLE
(BSA_TestScene) System.UriFormatException when opening trying to test paths in APK file?

### ISSUE THREAD

**Issue by AdamDoesThingsSometimes** [gwiazdorrr/BetterStreamingAssets#32]
Hi there,

Firstly, thank you so much for making this code available for public use, I'm already so blown away with being able to browse my own APK in this manner, it'll be so much better for debugging and copying things! :)

This could be an issue on my side, but I was wondering if you'd happen to know anything about System.UriFormatException when pressing the "Test Selected Paths" button in the example scene?

The scene loads my APK flawlessly and merrily lists the StreamingAssets content, but then immediately returns this message when I press "Test":

```
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
  at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x0007b] in <6d7c4c8dd3624dc596686fb7270ae1e6>:0 
  at System.Uri..ctor (System.String uriString) [0x00014] in <6d7c4c8dd3624dc596686fb7270ae1e6>:0 
  at Better.StreamingAssets.BSA_TestSceneGUI.get_StreamingAssetsPath () [0x00016] in C:\Users\adamc\Documents\Unity3D\CWLCommissioner\Assets\Plugins\BetterStreamingAssets\BSA_TestSceneGUI.cs:225 
  at Better.StreamingAssets.BSA_TestSceneGUI+<TestHarness>d__29.MoveNext () [0x00079] in C:\Users\adamc\Documents\Unity3D\CWLCommissioner\Assets\Plugins\BetterStreamingAssets\BSA_TestSceneGUI.cs:386 
  at Better.StreamingAssets.BSA_TestSceneGUI+<ErrorCatchingCoroutine>d__28.MoveNext () [0x0003b] in C:\Users\adamc\Documents\Unity3D\CWLCommissioner\Assets\Plugins\BetterStreamingAssets\BSA_TestSceneGUI.cs:365 
UnityEngine.Debug:Log (object)
Better.StreamingAssets.BSA_TestSceneGUI/<>c__DisplayClass26_0:<TestAllCoroutine>b__1 (System.Exception) (at Assets/Plugins/BetterStreamingAssets/BSA_TestSceneGUI.cs:314)
Better.StreamingAssets.BSA_TestSceneGUI/<ErrorCatchingCoroutine>d__28:MoveNext () (at Assets/Plugins/BetterStreamingAssets/BSA_TestSceneGUI.cs:369)
UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
Better.StreamingAssets.BSA_TestSceneGUI/<TestAllCoroutine>d__26:MoveNext () (at Assets/Plugins/BetterStreamingAssets/BSA_TestSceneGUI.cs:303)
UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
Better.StreamingAssets.BSA_TestSceneGUI:OnGUI () (at Assets/Plugins/BetterStreamingAssets/BSA_TestSceneGUI.cs:179)
```
It's very possible there's an issue with my pathing - I've tried lowercasing everything, removing spaces etc, but am unsure if there's anything I can try?

![image](https://user-images.githubusercontent.com/105390994/168679649-6c1dea12-3d6c-4c13-a9f9-7e3595758c94.png)

I popped in a debug.log for path just before it tries to load a file, and it comes back with
`Attempting to read 'cwltwo/arenasetup.txt' `

It looks like this local path is right from reading the lovely clear documentation (seriously, thank you, it's been a treat to use your work!), but wasn't sure if it's a Unity issue or something remarkably daft i've not done on my side?

If it helps, I'm using Unity 2021.3.2f1 (LTS) and have tried to this process in 2020.3.19f1 also.

Edit (again!): sorry, I just realised I forgot to note that the issue is for all the Read and Test Modes, and I've played around with the repetition count.

Thank you for your time :)

**Comment by AdamDoesThingsSometimes** [comment]
Also apologies for the multiple edits! I hit enter without expecting it to actually post just a title! :)

**Comment by AdamDoesThingsSometimes** [comment]
Just realised I could test using iOS/PC mode, and it works perfectly - it may be that I'm misusing the tool truth be told

**Comment by AdamDoesThingsSometimes** [comment]
As an aside, I commented out the testHarness call (and all the error catching) and made a really primitive version... and it works perfectly! :)

I am overjoyed at your solution to so many problems, and can't wait to make android builds after so much of my own time trying to come up with a solution! :) Thank you so much again, I can't overstate how much time and pain you've saved me and many other developers! :) I'll leave a glowing review on the asset store, and am happy to chip in with any extra info if I can help with this issue. :)

**Comment by gwiazdorrr** [comment]
Thanks for the report, I'll need some time to process this and then I will get back to you!

**Comment by gwiazdorrr** [comment]
Finally remembered to look at this. Seems that loading from a jar using WWW/UnityWebRequest is hopeless in Editor. So instead of that, I just decided to handle errors better with 12d6df3ac02b4ad0cf1216f1d02d187ffebe51c2. Thanks for noticing this!

**Comment by AdamDoesThingsSometimes** [comment]
That's great! :) Thank you again, BetterStreamingAssets was a godsend for this project :)
