### ISSUE TITLE
not worked  on  assetbundle with offset

### ISSUE THREAD

**Issue by milesmou** [gwiazdorrr/BetterStreamingAssets#33]
not worked on  assetbundle with offset

**Comment by backjy** [comment]
Modify with:
Fild: BSA_SubReadOnlyStream.cs
Line: 119
return m_position - m_offset;

        public override long Seek(long offset, SeekOrigin origin)
        {
            ThrowIfDisposed();

            if ( origin == SeekOrigin.Begin )
            {
                m_position = m_actualStream.Seek(m_offset + offset, SeekOrigin.Begin);
            }
            else if ( origin == SeekOrigin.End )
            {
                m_position = m_actualStream.Seek(m_offset + Length + offset, SeekOrigin.End);
            }
            else
            {
                m_position = m_actualStream.Seek( offset, SeekOrigin.Current);
            }
            return m_position - m_offset;
        }

**Comment by gwiazdorrr** [comment]
Could you share more details?
