### ISSUE TITLE
exception when using Unity Patch functionality

### ISSUE THREAD

**Issue by vendetta1987** [gwiazdorrr/BetterStreamingAssets#35]
Hi,
I recently noticed my app throwing an exception during startup when using the builtin Unity patch functionality. It allows patching the previously installed app for faster development ([link](https://docs.unity3d.com/Manual/android-AppPatching.html)). In short a blob with updated binary data is injected into the startup process, so to say.
This collides with your plugin around [here](https://github.com/gwiazdorrr/BetterStreamingAssets/blob/084dd2927d75ed1a1ae0eec0e747aefbff166f94/Runtime/BSA_BetterStreamingAssets.cs#L549). The blob file is provided instead of the APK and can't be read due to missing privileges of some sort.
I circumvented it for the time beeing by adding a check for the path extension but maybe you can come up with something more universal.

**Comment by gwiazdorrr** [comment]
Solved with dea9e36c78140cbd39d783b41a1e2a363175d3e9.
