### ISSUE TITLE
Access folder in streamingAssets folder in Android

### ISSUE THREAD

**Issue by yli223** [gwiazdorrr/BetterStreamingAssets#37]
Hey,

I am new to this, and I wonder how can I access the folder path in streamingAssets after building in Android from Unity? I have a NLP model storing in streamingAssets, and I need the path to run it in Android device. How can I use BetterStreamingAssets to approach it?

Thanks in advance for your help!

**Comment by gwiazdorrr** [comment]
BSA can give you Streams that represent files. Whatever you are using needs to accept Stream as a parameter rather than file path.
