### ISSUE TITLE
I cannot use this plugin on android.

### ISSUE THREAD

**Issue by mastudio356** [gwiazdorrr/BetterStreamingAssets#39]
The program to retrieve files from Assets/StreamingAssets using this plugin **works** on **PC and IOS**, but **not** on **android**. I have also installed a workaround program for android, but it has some errors. (If I write as instructed, /Users/_MyName_/_ProjectName_/Assets/Plugins/BetterStreamingAssets/BetterStreamingAssetsCustom.cs(24,24): Error CS0759: No Defining declaration found for implementing declaration of partial method 'BetterStreamingAssetscustom.AndroidIsCom AndroidIsComCom': Error CS0759: No defining declaration found for implementing declaration of partial method 'BetterStreamingAssetscustom.AndroidIsComCom' (CS0759). It is possible that I have put the workaround program in the wrong way, but I would like to solve the problem if possible, please advise. Thanks for your support.

**Comment by gwiazdorrr** [comment]
You are likely trying to add a partial method from a different assembly, this is not going to work. Please use the static event instead: https://github.com/gwiazdorrr/BetterStreamingAssets/blob/99c6458a5b4c09014e19df90e863744658cd51d7/Runtime/BSA_BetterStreamingAssets.cs#L46

**Comment by mastudio356** [comment]
I changed the code but it did not work properly with an error.
" /Users/Myname/Projectname/Assets/Plugins/BetterStreamingAssets/BetterStreamingAssetsCustom.cs(43,43): Warning CS0067: The event 'Be CompressedStreamingAssetFound' is never used (CS0067)"

```csharp
using System;

public static class BetterStreamingAssetsCustom
{
    public static event Func<string, bool> CompressedStreamingAssetFound;

    static BetterStreamingAssetsCustom()
    {
        // Register the event handler
        CompressedStreamingAssetFound += AndroidIsCompressedFileStreamingAsset;
    }

    private static bool AndroidIsCompressedFileStreamingAsset(string path)
    {
        if (path == "assets/my_custom_plugin_settings.json")
        {
            return false;
        }

        // Add any additional logic here if needed

        return true;
    }
}
```
Sorry, but I need additional support. I am new to development and don't know much. Thanks for the appropriate support.

**Comment by gwiazdorrr** [comment]
Replace:
```cs
CompressedStreamingAssetFound += AndroidIsCompressedFileStreamingAsset;
```

With:
```cs
BetterStreamingAssets.CompressedStreamingAssetFound += AndroidIsCompressedFileStreamingAsset;
```

**Comment by mastudio356** [comment]
When I use "CompressedStreamingAssetFound" I get "/Users/2023n1048/MUSICSTAR/Assets/Plugins/BetterStreamingAssets/BetterStreamingAssetsCustom.cs(30,30): Error CS0117: 'BetterStreamingAssets' does not contain a definition for 'CompressedStreamingAssetFound' (CS0117)" error and "/Users/2023n1048/MUSICSTAR/Assets/Plugins/BetterStreamingAssets/BetterStreamingAssetsCustom.cs(43,43): Warning CS0067: The event 'BetterStreamingAssetsCustom.CompressedStreamingAssetFound' is never used (CS0067)"

**Comment by mastudio356** [comment]
```csharp
using System;

public static class BetterStreamingAssetsCustom
{
    public static event Func<string, bool> CompressedStreamingAssetFound;

    static BetterStreamingAssetsCustom()
    {
        // error CS0117
        BetterStreamingAssets.CompressedStreamingAssetFound += AndroidIsCompressedFileStreamingAsset;
    }

    private static bool AndroidIsCompressedFileStreamingAsset(string path)
    {
        if (path == "assets/my_custom_plugin_settings.json")
        {
            return false;
        }

        // Add any additional logic here if needed

        return true;
    }
}
```

**Comment by gwiazdorrr** [comment]
Make sure you use the latest version from the github. I can't help you further.
