### ISSUE TITLE
Support for OpenHarmony

### ISSUE THREAD

**Issue by swallowguo** [gwiazdorrr/BetterStreamingAssets#42]
OpenHarmony is a new mobile operating system, which has already been supported by TuanJie Engine of Unity. And the BetterStreamingAssets needs some platform adaptation codes to support it as well. So could i submit these codes to this repository? I have completed the functional testing. The code example is as follows：

        public static void Initialize(string dataPath, string streamingAssetsPath)
        {
            #if UNITY_OPENHARMONY
                dataPath = "/data/storage/el1/bundle/entry.hap";
            #endif
        ... ... ... ...

**Comment by gwiazdorrr** [comment]
I have no knowledge of OpenHarmony nor I have capabilities to test it. Generally if you want to contribute, create a pull request.

That said, with 6e39e486962dee2327385b4db424d944c859f48b you can now pass the `dataPath` from outside, where you call `BetterStreamingAssets.Initialize`. So you no longer have to modify the BSA itself. Hope this helps!
