### ISSUE TITLE
Unable to return file paths of StreamingAssets files.

### ISSUE THREAD

**Issue by JakobDutch** [gwiazdorrr/BetterStreamingAssets#43]
Hi there,

Hopefully, I am in the correct place to ask for help with my issue. 
Currently, I'm building a VR application using Meta Quest 3 VR glasses. One of the important aspects of the application is that certain objects need to be loaded during runtime and be accessible from the outside (outside the editor (e.g. file explorer)). In the editor, I do this using the StreamingAssets folder and an OBJLoader called Runtime OBJ Importer. In the editor, everything works fine and dandy, but when I upload my APK build to the glasses, it seems that no files get found and thus no files get loaded in. 

here's the code that differentiates between the Unity Editor and the APK: (GitHub for some reason doesn't show code insert correctly (sorry))
`
void Start()
{
    BetterStreamingAssets.Initialize();
    Debug.Log("Getting all files..." + BetterStreamingAssets.GetFiles("\\")); // Log message indicating file gathering process

    if (Application.platform == RuntimePlatform.Android)
    {
        filesArray = BetterStreamingAssets.GetFiles("\\", "*.*", SearchOption.AllDirectories);
        Debug.Log("Getting all files..." + BetterStreamingAssets.GetFiles("\\")); // Log message indicating file gathering process
    }
    else
    {
        filesArray = Directory.GetFiles(Application.streamingAssetsPath, "*.*", SearchOption.AllDirectories); // List to store file names
        Debug.Log("Getting all files..." + Application.streamingAssetsPath); // Log message indicating file gathering process
    }
    files = new List<string>(filesArray);
    Containers = new GameObject[filesArray.Length];
    Trash = new GameObject[filesArray.Length];
    for (int i = 0; i < files.Count; i++)
    {
        Debug.Log(files[i]);
    }
    RemoveDuplicatesAndMeta();

    AssignObjToArray();
}
`
EDIT: Using "/" instead of "double \\" now returns file paths. Unfortunately, I need the full root of the folders as well... (e.g. /data/app/~~4rWYwDQq-8wtLaJsyFF-LA==/com.FAT100.StarterApp-uBE16dDsV0WzTAOYTjcMiQ==/base.apk/assets/...)
I am unable to hardcode this since the characters after "squiggly line" are not static (every build has different chars and so when I update the chars differ again).
Is there any way to return the full path to specific files?

What I'm wondering is how I can correctly return the file paths (which I need to load in objects using Runtime OBJ Importer) of the files that I place in the StreamingAssets folder while running the APK on the Meta Quest 3 VR glasses. 
When using an APK editor application I see my files correctly and in the correct folders. The only different thing is the tool folder which is now called 'assets'. (see image)
![image](https://github.com/gwiazdorrr/BetterStreamingAssets/assets/94533321/bd951843-0f59-4128-b543-c9b05bf36312)

Another side note: I saw that reading files from APK is a bit funky, but when you use lower-case it should be fine, after building the APK, some files automatically get renamed using upper-case letters for some reason...

**Comment by JakobDutch** [comment]
Thanks for the reply @gwiazdorrr 
In the meantime, I've been trying out a lot of different combinations. I used `filesArray = BetterStreamingAssets.GetFiles("/", "*.*", SearchOption.AllDirectories)` to return file paths. This returns the correct file path relative to the `assets` folder (APK version of Streaming Assets). 
The problem with that is that the string it returns doesn't seem to be recognized. To resolve this issue I've been using `BetterStreamingAssets.Root` to return the full file path and combine them using `Path.Combine(BetterStreamingAssets.Root, str` str being a string from filesArray inside of a for-each loop.

The problem I am now struggling with is that when I throw the `Path.Combine` file path in `File.Exists()` it returns false.
I've tried about 10-20 different variations of file paths and all get stuck on this.

File path examples: 
`/jar:file:///data/app/~~ohWEDtnAvxpfkPlepzLUAw==/com.FAT100.StarterApp-YVkJYOYlhDkfapwE8Sxktg==/base.apk!/assets/Containers/obj_models/0.obj`
`/data/app/~~ohWEDtnAvxpfkPlepzLUAw==/com.FAT100.StarterApp-YVkJYOYlhDkfapwE8Sxktg==/base.apk/assets/Containers/ob_models/0.obj`

**Comment by gwiazdorrr** [comment]
If you see stuff like `jar:file:///`, it means that it points to _inside_ of an archive, not a standalone file. `File.Exists` does peek into archive.

**Comment by JakobDutch** [comment]
@gwiazdorrr 
Ah I see, I was unaware of that…
Could you perhaps give an example path derived from me example paths that would be accepted in `File.Exists()`?
This is the final issue in my project and I’ve been struggling with it for weeks…

**Comment by gwiazdorrr** [comment]
Please read more about Streaming Assets: https://docs.unity3d.com/Manual/StreamingAssets.html

On Android platforms Streaming Assets are read only, hosted inside an archive. BSA allows you to enumerate them and read them directly, but they still won't be available as standalone files. If whatever you need Streaming Assets for accepts streams or path + file offset, you can make it work with BSA.

What you are experiencing is a fairly common misconception due to the fact that for _some_ platforms and, more crucially, in the editor you are allowed to access and modify Streaming Assets with regular System.IO.
