### ISSUE TITLE
SeekOrigin.End wrong behavior 

### ISSUE THREAD

**Issue by fdsagizi** [gwiazdorrr/BetterStreamingAssets#6]
your example on main page not work ( seek from end ):

// as stream, last 10 bytes
byte[] footer = new byte[10];
using (var stream = BetterStreamingAssets.OpenRead("Foo/bar.data"))
{
    stream.Seek(footer.Length, SeekOrigin.End); // cursor will be on wrong position ( over of file )
    stream.Read(footer, 0, footer.Length);
}

**Comment by gwiazdorrr** [comment]
Thanks, fixed in https://github.com/gwiazdorrr/BetterStreamingAssets/commit/0b634009569e9170d8dc264ae7b5db3edb2af4d0
