### ISSUE TITLE
System.IO.FileNotFoundException: File not found on Oculus Quest

### ISSUE THREAD

**Issue by CheapDevotion** [gwiazdorrr/BetterStreamingAssets#8]
I'm getting a `System.IO.FileNotFoundException: File not found` exception when using the plugin on the Oculus Quest. I have verified that the files exist in the StreamingAssets directory, and are included in the APK. The code works correctly in the Editor.

**Comment by gwiazdorrr** [comment]
Any warnings? Do you have a full call stack? Which Unity version? Anything fancy about how you make your build?
